### ISSUE TITLE
代理为什么还有 client/server

### ISSUE THREAD

**Issue by Jsharkc** [sakeven/ssng#5]
Hi，麻烦请教一下，代理为什么还有客户端和服务端呢？

**Comment by sakeven** [comment]
因为服务端的特殊协议，浏览器本身不支持的。浏览器一般只支持 http,socks5 这些协议。
所以需要客户端在本地将协议做一次转换，转换成 http 或者是 socks5 代理协议。

**Comment by Jsharkc** [comment]
蟹蟹٩('ω')و
